### ISSUE TITLE
（テスト）ぴよぴよはおかしい

### ISSUE THREAD

**Issue by DRVV** [kjybinp/zikeiretu#1]
`readme.md` 第２行末尾
「ぴよぴよ」とありますが，実装とは異なる記述なので修正すべきです。

**Comment by kjybinp** [comment]
重要なご指摘ありがとうございます。確かに、 しっかり記述するなら、「ぴよぴよ、ぴよぴよ」ですね。修正に時間がかかるので、contributeしてもらえると幸いです。
